import { Inter } from "next/font/google";
import "./globals.css";
import { clsx } from "clsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NETHMAl_Portfolio",
  description: "Generated by Nethmal",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={clsx(inter.variable, "bg-background text-foreground")
      }>{children}</body>
    </html>
  );
}
